	IMPLICIT NONE

	INCLUDE 'INITIAL_PARAMETERS.inc'
	INCLUDE 'NOOFPARTICLES.inc'
	INCLUDE 'UMBRELLA_SAMPLING.inc'
	INCLUDE 'POSITIONS.inc'
	INCLUDE 'ENERGY_HCHI.inc'	

	INTEGER ICYCLE
	DOUBLE PRECISION ENERGY,PRESSURE,V_HCHI,V_WCA

	INTEGER NOOFOUTPUTFILES,I
	PARAMETER (NOOFOUTPUTFILES=5)
	CHARACTER*123 F1,F2(NOOFOUTPUTFILES)

	OPEN(11,FILE='OUTPUTFILES')
	DO I=1,NOOFOUTPUTFILES
        READ(11,'(a)') F1
        F2(I) = F1
	ENDDO
	CLOSE(11)

	OPEN(20,FILE=F2(1))
	OPEN(21,FILE=F2(2))
	OPEN(22,FILE=F2(3))
	OPEN(23,FILE=F2(4))
	OPEN(24,FILE=F2(5))
	
	CALL POSITIONS_SUB
	CALL CELLLIST_MAPS_SUB
	CALL CELLLIST_LINKS_SUB
	CALL VERLETLIST_SUB
	CALL ENERGY_SUB(0,0,ENERGY,PRESSURE,V_HCHI,V_WCA)

	DO ICYCLE=1,NCYCLE
	  CALL MC_MOVE_SUB(ICYCLE,ENERGY,PRESSURE,V_HCHI,V_WCA)
	  IF(SW_ENSEMBLE.EQ.2)THEN
	  If(mod(ICYCLE,N).eq.0.and.icycle.ne.ncycle)Then
	  CALL MC_VOL_SUB(ICYCLE,ENERGY,PRESSURE,V_HCHI,V_WCA)
	  EndIf
	  ENDIF
C========DATA COLLECT=============================C
	IF(MOD(ICYCLE,NCOLLECT).EQ.0)THEN
	  DO I=1,N
	    WRITE(21,'(2(1x,I15),3(1x,g16.9))')ICYCLE,I,X(I),
     &		                               Y(I),CHI(I)
	  ENDDO
	  
          WRITE(22,'(1(1x,I15),5(1x,g16.9))')ICYCLE,ENERGY,PRESSURE,
     &	  V_WCA,V_HCHI,
     &	  DFLOAT(N)/(BOXX*BOXY)
	ENDIF

	IF(ICYCLE.EQ.NCYCLE)THEN
	  DO I=1,N
	    WRITE(23,'(1(1x,I15),3(1x,g16.9))')I,X(I),Y(I),CHI(I)
	  ENDDO
	ENDIF
C========DATA COLLECT=============================C
	ENDDO

	CLOSE(20)
	CLOSE(21)	
	CLOSE(22)
	CLOSE(23)
	CLOSE(24)
	
	STOP
	END
